# -*- coding: utf-8 -*-
"""for_loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dmrnah4I8tAtIZtDmkt2BqG_vG714Fhf
"""

#CS175
#Lucas Vandenakker
#a_e_i_o_u

str1 = input("Please enter a string: ")
lowerStr1 = str1.lower()
vowels = 0
constants = 0

for i in lowerStr1:
  if (i == 'a' or i == 'e' or i == 'i' or i == 'o' or i == 'u'):
    vowels+=1
  elif(i == " "):
    pass
  else:
    constants+=1

print(f"There are {vowels} vowels and {constants} constsnts in the word {str1}")

#CS175
#Lucas Vandenakker
#mulitplication_table

num1 = int(input("Enter a whole number: "))

for i in range(1,11):
  result = i* num1
  print(f"{num1} x {i} = {result}")

#CS175
#Lucas Vandenakker
#dictionary

student_grades = {
    	"Alice": 85,
    	"Bob": 92,
    	"Charlie": 78,
    	"Diana": 88,
    	"Eve": 91
	}

for i,j in student_grades.items():
  print(f"{i} is {j} years old")

#CS175
#Lucas Vandenakker
#even_or_odd_counter

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even = 0
evenNum = []
odd = 0
oddNum = []

for i in numbers:
  if i % 2 == 0:
    even+=1
    evenNum.append(i)
  else:
    odd+=1
    oddNum.append(i)

print(f"There are {odd} odd numbers: {oddNum}")
print(f"There are {even} even numbers: {evenNum}")

#CS175
#Lucas Vandenakker
#maxAndMin

numbers = [3, 5, 7, 2, 8, -1, 4]

max = numbers[0]
min = numbers[0]

for i in numbers:
  if (i > max):
    max = i
  elif( i < min):
    min = i

print(f"The largest value in the list is {max}")
print(f"The smallest value in the list is {min}")