# -*- coding: utf-8 -*-
"""grade_Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16RYTR_65CacpqRI87N5eO8fIPSn7W3I7
"""

#CS175
#Lucas Vandenakker
#Grade_Calculator

grades = [81, 92, 88, 64, 72, 80, 99, 100]

letterGrade = ""
total = 0
numTimes = 0

for i in grades:
  numTimes += 1
  total += i

average = total/numTimes
if (average < 60):
  letterGrade = "F"
elif(average >= 60 and average < 70):
  letterGrade = "D"
elif( average>= 70 and average < 80):
  letterGrade = "C"
elif(average >= 80 and average < 90):
  letterGrade = "B"
elif(average >= 90):
  letterGrade = "A"

print(f"The students average grade was {average}, so they got an {letterGrade}")

#CS175
#Lucas Vandenakker
#for-loop

list1 = [2, 4, 6, 8]
for i in list1:
  i = i**2
  print(i)