# -*- coding: utf-8 -*-
"""series_of_commissions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16RYTR_65CacpqRI87N5eO8fIPSn7W3I7
"""

#CS175
#Lucas Vandenakker
#series_of_commissions

i = True
while(i):
  sales = float(input("Enter your total value in sales : $"))
  commisionrate = int(input("Enter your commision rate(ex: 50 is 50% or 25 is 25%)"))
  commision = sales * (commisionrate/100)

  print(f"Your total price is ${commision:,}")

  userInput = input("Would you like to go again?(enter 'yes' to go again)")
  if(userInput != "yes"):
    i = False
  else:
    i = True